-------------------- Log Start | Mon Feb  5 14:48:45 2024 --------------------
data_path: /home/pi/printer_data
is_default_data_path: False
config_file: /home/pi/printer_data/config/moonraker.conf
startup_warnings: []
verbose: False
debug: False
asyncio_debug: False
is_backup_config: False
is_python_package: False
instance_uuid: 44e42bf3b1aa4a6390e0ef0b153be3c4
unix_socket_path: /home/pi/printer_data/comms/moonraker.sock
software_version: v0.8.0-308-g71b46cc
git_branch: master
git_remote: origin
git_repo_url: https://github.com/Arksine/moonraker.git
modified_files: []
unofficial_components: []
log_file: /home/pi/printer_data/logs/moonraker.log
python_version: 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]
launch_args: /home/pi/moonraker-env/bin/python /home/pi/moonraker/moonraker/moonraker.py -d /home/pi/printer_data
msgspec_enabled: False
uvloop_enabled: False

#################### Moonraker Configuration ####################

[server]
host = 0.0.0.0
port = 7125
klippy_uds_address = /home/pi/printer_data/comms/klippy.sock

[authorization]
trusted_clients = 
	127.0.0.1
	10.0.0.0/8
	127.0.0.0/8
	169.254.0.0/16
	172.16.0.0/12
	192.168.0.0/16
	FE80::/10
	::1/128
cors_domains = 
	*.lan
	*.local
	*://localhost
	*://localhost:*
	*://my.mainsail.xyz
	*://app.fluidd.xyz

[octoprint_compat]

[history]

[update_manager]
channel = dev
refresh_interval = 168

[update_manager trad_rack]
type = git_repo
path = ~/trad_rack_klippy_module
origin = https://github.com/Annex-Engineering/TradRack.git
primary_branch = main
managed_services = klipper

[update_manager belay]
type = git_repo
path = ~/belay_klippy_module
origin = https://github.com/Annex-Engineering/Belay.git
primary_branch = main
managed_services = klipper

[update_manager KlipperScreen]
type = git_repo
path = ~/KlipperScreen
origin = https://github.com/KlipperScreen/KlipperScreen.git
virtualenv = ~/.KlipperScreen-env
requirements = scripts/KlipperScreen-requirements.txt
system_dependencies = scripts/system-dependencies.json
managed_services = KlipperScreen

[update_manager mainsail-config]
type = git_repo
primary_branch = master
path = ~/mainsail-config
origin = https://github.com/mainsail-crew/mainsail-config.git
managed_services = klipper

[update_manager mainsail]
type = web
channel = stable
repo = mainsail-crew/mainsail
path = ~/mainsail

[file_manager]
enable_object_processing = True

[update_manager cartographer]
type = git_repo
path = ~/cartographer-klipper
channel = dev
origin = https://github.com/Cartographer3D/cartographer-klipper.git
env = ~/klippy-env/bin/python
requirements = requirements.txt
install_script = install.sh
is_system_service = False
managed_services = klipper
info_tags = 
	desc=Cartographer Probe

#################################################################
All Configuration Files:
/home/pi/printer_data/config/moonraker.conf
#################################################################

Database Versions: pylmdb = 1.4.1, lmdb = (0, 9, 29)
Unsafe Shutdown Count: 88

System Info:

***python***
  version: (3, 11, 2, 'final', 0)
  version_string: 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]

***cpu_info***
  cpu_count: 4
  bits: 64bit
  processor: aarch64
  cpu_desc: 
  serial_number: 812c0b9b3c12713d
  hardware_desc: BCM2835
  model: Raspberry Pi 5 Model B Rev 1.0
  total_memory: 4143408
  memory_units: kB

***sd_info***
  manufacturer_id: 27
  manufacturer: Unknown
  oem_id: 5048
  product_name: SD64G
  product_revision: 6.0
  serial_number: daaeb8db
  manufacturer_date: 1/2023
  capacity: 58.0 GiB
  total_bytes: 62226694144

***distribution***
  name: Debian GNU/Linux 12 (bookworm)
  id: debian
  version: 12
  version_parts: {'major': '12', 'minor': '', 'build_number': ''}
  like: 
  codename: bookworm
  release_info: {}

***virtualization***
  virt_type: none
  virt_identifier: none

***network***

***canbus***

***Allowed Services***
  klipper_mcu
  webcamd
  MoonCord
  KlipperScreen
  moonraker-telegram-bot
  moonraker-obico
  sonar
  crowsnest
  octoeverywhere
  ratos-configurator
Module libcamera unavailble, import failed

Systemd unit moonraker.service:
unit_name: moonraker.service
is_default: True
manager: systemd
Properties:
**Requires=['-.mount', 'network-online.target', 'system.slice', 'sysinit.target']
**After=['basic.target', 'sysinit.target', 'network-online.target', 'system.slice', '-.mount', 'systemd-journald.socket']
**SupplementaryGroups=['moonraker-admin']
**EnvironmentFiles=/home/pi/printer_data/systemd/moonraker.env
**ExecStart=/home/pi/moonraker-env/bin/python $MOONRAKER_ARGS
**WorkingDirectory=/home/pi/moonraker
**FragmentPath=/etc/systemd/system/moonraker.service
**Description=API Server for Klipper SV1
**User=pi

Systemd unit klipper.service:
unit_name: klipper.service
is_default: True
manager: systemd
Properties:
**Requires=['sysinit.target', '-.mount', 'system.slice']
**After=['network-online.target', 'sysinit.target', 'system.slice', 'basic.target', '-.mount', 'systemd-journald.socket']
**SupplementaryGroups=[]
**EnvironmentFiles=/home/pi/printer_data/systemd/klipper.env
**ExecStart=/home/pi/klippy-env/bin/python $KLIPPER_ARGS
**WorkingDirectory=/home/pi/klipper
**FragmentPath=/etc/systemd/system/klipper.service
**Description=Klipper 3D Printer Firmware SV1
**User=pi
Git Repo moonraker: No warnings detected
Git Repo klipper: Warnings detected:
  Repo has untracked source files: ['klippy/extras/belay.py', 'klippy/extras/gcode_shell_command.py', 'klippy/extras/trad_rack.py']
Git Repo trad_rack: No warnings detected
Git Repo belay: No warnings detected
Git Repo KlipperScreen: No warnings detected
Git Repo mainsail-config: No warnings detected
Git Repo cartographer: Warnings detected:
  Repo is dirty.  Detected the following modifed files: ['install.sh']
Klipper Version: v0.12.0-102-g9f41f53c-dirty
2024-02-05 14:48:45,265 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.1.73
2024-02-05 14:48:45,266 [application.py:log_request()] - 101 GET /websocket (192.168.1.73) [_TRUSTED_USER_] 1.00ms
2024-02-05 14:48:45,266 [websockets.py:open()] - Websocket Opened: ID: 140734289750352, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36, Host Name: 192.168.1.244
2024-02-05 14:48:45,277 [websockets.py:_handle_identify()] - Websocket 140734289750352 Client Identified - Name: mainsail, Version: 2.9.1, Type: web
2024-02-05 14:48:54,462 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2024-02-05 14:48:54,713 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2024-02-05 14:49:01,414 [common.py:build_error()] - JSON-RPC Request Error - Requested Method: printer.gcode.script, Code: 400, Message: 
Printer is not ready
The klippy host software is attempting to connect.  Please
retry in a few moments.

2024-02-05 14:50:19,910 [application.py:prepare()] - Upload Request Received from 192.168.1.73
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryVsrDKNelnLtRnZBA
2024-02-05 14:50:19,915 [application.py:post()] - Processing Uploaded File: printer.cfg
2024-02-05 14:50:19,919 [application.py:log_request()] - 201 POST /server/files/upload (192.168.1.73) [_TRUSTED_USER_] 9.40ms
2024-02-05 14:50:21,003 [klippy_connection.py:close()] - Error closing Klippy Unix Socket
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/components/klippy_connection.py", line 769, in close
    await self.writer.wait_closed()
  File "/usr/lib/python3.11/asyncio/streams.py", line 350, in wait_closed
    await self._protocol._get_close_waiter(self)
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 995, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
2024-02-05 14:50:21,003 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2024-02-05 14:50:21,003 [common.py:build_error()] - JSON-RPC Request Error - Requested Method: printer.info, Code: 503, Message: Klippy Disconnected
2024-02-05 14:50:21,254 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2024-02-05 14:50:21,520 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2024-02-05 14:50:21,521 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2024-02-05 14:50:21,522 [klippy_connection.py:_check_ready()] - 
Unknown pin chip name 'probe'

Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted

2024-02-05 14:50:52,490 [application.py:prepare()] - Upload Request Received from 192.168.1.73
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryQskmNI78NQB096qm
2024-02-05 14:50:52,495 [application.py:post()] - Processing Uploaded File: printer.cfg
2024-02-05 14:50:52,497 [application.py:log_request()] - 201 POST /server/files/upload (192.168.1.73) [_TRUSTED_USER_] 7.16ms
2024-02-05 14:50:53,129 [klippy_connection.py:close()] - Error closing Klippy Unix Socket
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/components/klippy_connection.py", line 769, in close
    await self.writer.wait_closed()
  File "/usr/lib/python3.11/asyncio/streams.py", line 350, in wait_closed
    await self._protocol._get_close_waiter(self)
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 995, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
2024-02-05 14:50:53,130 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2024-02-05 14:50:53,130 [common.py:build_error()] - JSON-RPC Request Error - Requested Method: printer.info, Code: 503, Message: Klippy Disconnected
2024-02-05 14:50:54,384 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2024-02-05 14:50:54,650 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2024-02-05 14:50:54,651 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2024-02-05 14:50:54,651 [klippy_connection.py:_check_ready()] - 
Unknown pin chip name 'probe'

Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted

2024-02-05 14:51:55,247 [application.py:prepare()] - Upload Request Received from 192.168.1.73
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryCxxxpSCe7WvDXrTz
2024-02-05 14:51:55,255 [application.py:post()] - Processing Uploaded File: printer.cfg
2024-02-05 14:51:55,257 [application.py:log_request()] - 201 POST /server/files/upload (192.168.1.73) [_TRUSTED_USER_] 10.45ms
2024-02-05 14:51:55,902 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2024-02-05 14:51:57,155 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2024-02-05 14:51:57,423 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2024-02-05 14:51:57,423 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2024-02-05 14:51:57,423 [klippy_connection.py:_check_ready()] - 
Unknown pin chip name 'probe'

Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted

2024-02-05 14:52:06,560 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2024-02-05 14:52:07,815 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2024-02-05 14:52:08,082 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2024-02-05 14:52:08,082 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2024-02-05 14:52:08,082 [klippy_connection.py:_check_ready()] - 
Unknown pin chip name 'probe'

Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted

2024-02-05 14:52:31,305 [application.py:prepare()] - Upload Request Received from 192.168.1.73
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryaY6j0p3ZnBN5UoAW
2024-02-05 14:52:31,312 [application.py:post()] - Processing Uploaded File: printer.cfg
2024-02-05 14:52:31,314 [application.py:log_request()] - 201 POST /server/files/upload (192.168.1.73) [_TRUSTED_USER_] 9.07ms
2024-02-05 14:52:31,946 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2024-02-05 14:52:33,200 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2024-02-05 14:52:33,467 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2024-02-05 14:52:33,468 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2024-02-05 14:52:33,468 [klippy_connection.py:_check_ready()] - 
Unknown pin chip name 'probe'

Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted

2024-02-05 14:52:54,386 [application.py:prepare()] - Upload Request Received from 192.168.1.73
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryKeOieDpZO5AiXb0q
2024-02-05 14:52:54,393 [application.py:post()] - Processing Uploaded File: printer.cfg
2024-02-05 14:52:54,395 [application.py:log_request()] - 201 POST /server/files/upload (192.168.1.73) [_TRUSTED_USER_] 9.39ms
2024-02-05 14:52:55,035 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2024-02-05 14:52:56,289 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2024-02-05 14:52:56,557 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2024-02-05 14:52:56,557 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2024-02-05 14:52:56,558 [klippy_connection.py:_check_ready()] - 
Unknown pin chip name 'probe'

Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted

2024-02-05 14:53:12,917 [application.py:prepare()] - Upload Request Received from 192.168.1.73
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryrm6hWZtBT3we7nx5
2024-02-05 14:53:12,924 [application.py:post()] - Processing Uploaded File: printer.cfg
2024-02-05 14:53:12,926 [application.py:log_request()] - 201 POST /server/files/upload (192.168.1.73) [_TRUSTED_USER_] 8.82ms
2024-02-05 14:53:13,286 [klippy_connection.py:close()] - Error closing Klippy Unix Socket
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/components/klippy_connection.py", line 769, in close
    await self.writer.wait_closed()
  File "/usr/lib/python3.11/asyncio/streams.py", line 350, in wait_closed
    await self._protocol._get_close_waiter(self)
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 995, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
2024-02-05 14:53:13,286 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2024-02-05 14:53:13,287 [common.py:build_error()] - JSON-RPC Request Error - Requested Method: printer.info, Code: 503, Message: Klippy Disconnected
2024-02-05 14:53:14,539 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2024-02-05 14:53:14,806 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2024-02-05 14:53:14,806 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2024-02-05 14:53:14,806 [klippy_connection.py:_check_ready()] - 
Option 'position_max' in section 'stepper_z' must be specified

Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted

2024-02-05 14:53:25,716 [application.py:prepare()] - Upload Request Received from 192.168.1.73
Content-Type: multipart/form-data; boundary=----WebKitFormBoundarymbfW9vzVlkuopEkx
2024-02-05 14:53:25,755 [application.py:post()] - Processing Uploaded File: printer.cfg
2024-02-05 14:53:25,757 [application.py:log_request()] - 201 POST /server/files/upload (192.168.1.73) [_TRUSTED_USER_] 41.23ms
2024-02-05 14:53:26,087 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2024-02-05 14:53:27,340 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2024-02-05 14:53:27,612 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2024-02-05 14:53:27,613 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2024-02-05 14:53:27,613 [klippy_connection.py:_check_ready()] - 
Unknown pin chip name 'probe'

Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted

2024-02-05 14:54:32,756 [application.py:prepare()] - Upload Request Received from 192.168.1.73
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryeKywHqAJBhR6mflo
2024-02-05 14:54:32,761 [application.py:post()] - Processing Uploaded File: printer.cfg
2024-02-05 14:54:32,763 [application.py:log_request()] - 201 POST /server/files/upload (192.168.1.73) [_TRUSTED_USER_] 7.22ms
2024-02-05 14:54:33,084 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2024-02-05 14:54:34,338 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2024-02-05 14:54:34,605 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2024-02-05 14:54:34,605 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2024-02-05 14:54:34,605 [klippy_connection.py:_check_ready()] - 
Unknown pin chip name 'probe'

Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted

2024-02-05 14:55:46,801 [application.py:prepare()] - Upload Request Received from 192.168.1.73
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryAMu21gDwgUO75bUX
2024-02-05 14:55:46,806 [application.py:post()] - Processing Uploaded File: printer.cfg
2024-02-05 14:55:46,808 [application.py:log_request()] - 201 POST /server/files/upload (192.168.1.73) [_TRUSTED_USER_] 7.66ms
2024-02-05 14:55:47,138 [klippy_connection.py:close()] - Error closing Klippy Unix Socket
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/components/klippy_connection.py", line 769, in close
    await self.writer.wait_closed()
  File "/usr/lib/python3.11/asyncio/streams.py", line 350, in wait_closed
    await self._protocol._get_close_waiter(self)
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 995, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
2024-02-05 14:55:47,138 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2024-02-05 14:55:47,138 [common.py:build_error()] - JSON-RPC Request Error - Requested Method: printer.info, Code: 503, Message: Klippy Disconnected
2024-02-05 14:55:48,391 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2024-02-05 14:55:48,658 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2024-02-05 14:55:48,658 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2024-02-05 14:55:48,659 [klippy_connection.py:_check_ready()] - 
Option 'mesh_main_direction' is not valid in section 'cartographer'

Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted

2024-02-05 14:56:14,409 [application.py:prepare()] - Upload Request Received from 192.168.1.73
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryGqWECmg7nWp3EoXb
2024-02-05 14:56:14,413 [application.py:post()] - Processing Uploaded File: printer.cfg
2024-02-05 14:56:14,415 [application.py:log_request()] - 201 POST /server/files/upload (192.168.1.73) [_TRUSTED_USER_] 6.45ms
2024-02-05 14:56:15,764 [klippy_connection.py:close()] - Error closing Klippy Unix Socket
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/components/klippy_connection.py", line 769, in close
    await self.writer.wait_closed()
  File "/usr/lib/python3.11/asyncio/streams.py", line 350, in wait_closed
    await self._protocol._get_close_waiter(self)
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 995, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
2024-02-05 14:56:15,765 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2024-02-05 14:56:15,765 [common.py:build_error()] - JSON-RPC Request Error - Requested Method: printer.info, Code: 503, Message: Klippy Disconnected
2024-02-05 14:56:16,016 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2024-02-05 14:56:16,283 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2024-02-05 14:56:16,284 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2024-02-05 14:56:16,284 [klippy_connection.py:_check_ready()] - 
Option 'mesh_main_direction' is not valid in section 'cartographer'

Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted

2024-02-05 14:57:43,379 [application.py:prepare()] - Upload Request Received from 192.168.1.73
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryuMIt8HNATFs7L7yr
2024-02-05 14:57:43,384 [application.py:post()] - Processing Uploaded File: printer.cfg
2024-02-05 14:57:43,386 [application.py:log_request()] - 201 POST /server/files/upload (192.168.1.73) [_TRUSTED_USER_] 8.00ms
2024-02-05 14:57:44,735 [klippy_connection.py:close()] - Error closing Klippy Unix Socket
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/components/klippy_connection.py", line 769, in close
    await self.writer.wait_closed()
  File "/usr/lib/python3.11/asyncio/streams.py", line 350, in wait_closed
    await self._protocol._get_close_waiter(self)
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 995, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
2024-02-05 14:57:44,735 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2024-02-05 14:57:44,735 [common.py:build_error()] - JSON-RPC Request Error - Requested Method: printer.info, Code: 503, Message: Klippy Disconnected
2024-02-05 14:57:44,987 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2024-02-05 14:59:16,569 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2024-02-05 14:59:16,569 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2024-02-05 14:59:16,570 [klippy_connection.py:_check_ready()] - 
mcu 'cartographer': Unable to connect
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Error configuring printer

2024-02-05 15:30:21,394 [klippy_connection.py:close()] - Error closing Klippy Unix Socket
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/components/klippy_connection.py", line 769, in close
    await self.writer.wait_closed()
  File "/usr/lib/python3.11/asyncio/streams.py", line 350, in wait_closed
    await self._protocol._get_close_waiter(self)
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 995, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
2024-02-05 15:30:21,394 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2024-02-05 15:30:21,394 [common.py:build_error()] - JSON-RPC Request Error - Requested Method: printer.info, Code: 503, Message: Klippy Disconnected
2024-02-05 15:30:21,646 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2024-02-05 15:31:53,230 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2024-02-05 15:31:53,230 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2024-02-05 15:31:53,232 [klippy_connection.py:_check_ready()] - 
mcu 'cartographer': Unable to connect
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Error configuring printer

2024-02-05 15:42:35,874 [klippy_connection.py:close()] - Error closing Klippy Unix Socket
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/components/klippy_connection.py", line 769, in close
    await self.writer.wait_closed()
  File "/usr/lib/python3.11/asyncio/streams.py", line 350, in wait_closed
    await self._protocol._get_close_waiter(self)
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 995, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
2024-02-05 15:42:35,874 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2024-02-05 15:42:35,875 [common.py:build_error()] - JSON-RPC Request Error - Requested Method: printer.info, Code: 503, Message: Klippy Disconnected
2024-02-05 15:42:36,126 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2024-02-05 15:42:50,689 [websockets.py:on_close()] - Websocket Closed: ID: 140734289750352 Close Code: 1001, Close Reason: None, Pong Time Elapsed: 5.42
2024-02-05 15:44:07,665 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2024-02-05 15:44:07,665 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2024-02-05 15:44:07,667 [klippy_connection.py:_check_ready()] - 
mcu 'cartographer': Unable to connect
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Error configuring printer

2024-02-05 16:01:54,615 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 192.168.1.73
2024-02-05 16:29:48,429 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.1.73
2024-02-05 16:29:48,430 [application.py:log_request()] - 101 GET /websocket (192.168.1.73) [_TRUSTED_USER_] 1.00ms
2024-02-05 16:29:48,430 [websockets.py:open()] - Websocket Opened: ID: 140734270074576, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36, Host Name: 192.168.1.244
2024-02-05 16:29:48,492 [websockets.py:_handle_identify()] - Websocket 140734270074576 Client Identified - Name: mainsail, Version: 2.9.1, Type: web
2024-02-05 16:29:52,425 [klippy_connection.py:_on_connection_closed()] - Klippy Connection Removed
2024-02-05 16:29:53,679 [klippy_connection.py:_do_connect()] - Klippy Connection Established
2024-02-05 16:29:56,210 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2024-02-05 16:29:56,210 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2024-02-05 16:29:56,460 [job_state.py:_handle_started()] - Job state initialized: standby
2024-02-05 16:29:56,726 [klippy_connection.py:_check_ready()] - Klippy ready
2024-02-05 16:29:57,219 [data_store.py:_init_sensors()] - Configuring available sensors: ['temperature_sensor Kraken', 'heater_bed', 'temperature_sensor cartographer_coil', 'extruder']
2024-02-05 17:02:06,018 [websockets.py:on_close()] - Websocket Closed: ID: 140734270074576 Close Code: None, Close Reason: None, Pong Time Elapsed: 7.58
2024-02-05 17:12:14,035 [application.py:log_request()] - 101 GET /websocket (192.168.1.73) [_TRUSTED_USER_] 0.77ms
2024-02-05 17:12:14,035 [websockets.py:open()] - Websocket Opened: ID: 140734270413712, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36, Host Name: 192.168.1.244
2024-02-05 17:12:14,342 [websockets.py:_handle_identify()] - Websocket 140734270413712 Client Identified - Name: mainsail, Version: 2.9.1, Type: web
2024-02-05 18:16:54,636 [authorization.py:_prune_conn_handler()] - Trusted Connection Expired, IP: 192.168.1.73
2024-02-05 18:38:38,102 [websockets.py:on_close()] - Websocket Closed: ID: 140734270413712 Close Code: None, Close Reason: None, Pong Time Elapsed: 4.06
